version: '3.8'
services:
  backend:
    build: ./contract-application
    ports:
      - "8080:8080"
    network_mode: host

  frontend:
    build: ./contract-ui
    ports:
      - "80:80"
    network_mode: host
